### ISSUE TITLE
[Bug] Generating java class in strage folder [sf#102]

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#104]
**Reported by *anonymous on 2009-03-26 15:35 UTC**
Hello everyone\!

I'm having a rather strange problem with JFlex's plugin for maven. It is generating my java source file containing the regular expression in hierarchy of folders which are named "Name = yytext\(\)" \ "substring\(0,yytext\(\)" \ "length\(\)\)".

Has anyone been through this before? I'm gonna attatch the POM file I'm using for the project.

**Comment by regisd** [comment]
We reproduce at head on `./jflex/examples/cup-java/target/generated-sources/jflex/"                      { return symbol(PACKAGE)/Scanner.java`

**Comment by regisd** [comment]
The problem obviously comes from the `LexSimpleAnalyzer`.

This is caused by the fact that

* the class is in the default package (the lex definition doesn't have a `package foo;` in the user code)
* the lex defines an action for "package": `  "package"                      { return symbol(PACKAGE); }`
