### ISSUE TITLE
typo in description of method zzRefill()

### ISSUE THREAD

**Issue by tbl0605** [jflex-de/jflex#169]
Hi,
In jflex/src/main/resources/jflex/skeleton.default and jflex/src/main/jflex/skeleton.nested (and maybe elsewhere) there's a little typo in description of method zzRefill().

@return      <code>false</code>, iff there was new input.

should be :
@return      <code>false</code>, if there was new input.

Thierry.

**Comment by schedulix** [comment]
"iff" is the mathematical abbreviation for "if and only if". This is a far stronger expression than a mere "if".
The expression "if there was new input then return false" doesn't define what to do if there was no new input.
The expression "if and only if there was new input then return false" defines that if there was no new input anything but false has to be returned. Since the return type is a boolean, true is forced

**Comment by tbl0605** [comment]
Hi Ronald,
Ok, I've learned something today ! :)
As english is not my mother language, I didn't know this kind of abbreviation !
In french this mathematical abbreviation is "ssi" :)

Sorry for the wrong bug report, I close it!

Thierry.
