### ISSUE TITLE
empty constructor ?

### ISSUE THREAD

**Issue by tarzanek** [jflex-de/jflex#180]
Hi guys
sorry for silly Q, but
is there a way how to generate just EMPTY constructor?

tia
L

**Comment by tarzanek** [comment]
weird, I hope to tag this as "question", can someone assign this label?

**Comment by lsf37** [comment]
There currently isn't a way to generate an empty constructor. The reason is that the scanner needs a Reader to read from. If you really need to separate those two steps of creating a scanner and setting a Reader, you could declare your own empty constructor in the class code `%{ .. %}` section that calls the generated constructor with `null` (depending on what the rest of your scanner does it might even be Ok to do nothing, but it'll be more robust to do the `null` call). You would then need an additional method to set the Reader that needs to be called before the first call to the scanner method.

Does that make sense?

**Comment by tarzanek** [comment]
OK, so this is what I was aware of and it kinda duplicates too much code for me (I inherit a class, but cannot inherit an empty constructor which isn't public :( )
thanks much for the answer and assuring me I didn't miss anything (and good job on jflex, like it very much! :) )
