### ISSUE TITLE
Build fails after JFlex upgrade

### ISSUE THREAD

**Issue by llbit** [jflex-de/jflex#190]
Hi, after upgrading to JFlex 1.6.1 from 1.4.3 the build for [ExtendJ](https://bitbucket.org/extendj/extendj) fails. I get the following error message:

        [jflex] 
        [jflex] Error in file "extendj/src/tmp/scanner/OriginalScanner.flex" (line 109): 
        [jflex] Unexpected character
        [jflex] 
        [jflex] <YYINITIAL> { {WhiteSpace} { } }
        [jflex] 
        [jflex]               ^
        [jflex] 

After a quick look at the change list I could not see why I would get this error. The whole scanner file is kinda large, but here is some context:

    NumericLiteral = 0 [_0-9a-fA-FxXlL.]* {FloatExponentPart}? {FloatSuffix}?
                   | [1-9] [_0-9a-fA-FxXlL.]* {FloatExponentPart}? {FloatSuffix}?
                   | \. [0-9] [_0-9a-fA-FxXlL.]* {FloatExponentPart}? {FloatSuffix}?
    FloatExponentPart = [eE] [_0-9fF]*
                 | [pP] [_0-9]+
                 | [eE] [+-] [0-9] [_0-9]*
                 | [pP] [+-] [0-9] [_0-9]*
    FloatSuffix = [fFdD]
    
    /* 3.10.4 Character Literals */
    SingleCharacter = [^\r\n\'\\]
    
    /* 3.10.5 String Literals */
    StringCharacter = [^\r\n\"\\]
    
    /* 3.10.6 Escape Sequences for Character and String Literals */
    OctalEscape = \\ {OctalDigit}
                | \\ {OctalDigit} {OctalDigit}
                | \\  {ZeroToThree} {OctalDigit} {OctalDigit}
    OctalDigit = [0-7]
    ZeroToThree = [0-3]
    
    %state STRING
    
    %%
    
    /* 3.6 White Space */
    <YYINITIAL> { {WhiteSpace} { } }
    
    /* 3.7 Comments */
    <YYINITIAL> { {Comment} { } }

**Comment by llbit** [comment]
Apparently the braces surrounding `{WhiteSpace} { }` are no longer allowed. Is this change documented?

**Comment by sarowe** [comment]
Hi Jesper,

It’s not that the braces surrounding {WhiteSpace} { } are no longer allowed.

Rather, the open curly brace after a <STATELIST> must now be followed by a newline.  This change happened in JFlex 1.5.0, I don’t recall why.  (I know because I tried to generate your java4 scanner from the full spec with JFlex 1.4.3, 1.5.0, 1.5.1, 1.6.0 and 1.6.1.)

After I converted these:

    <YYINITIAL> { {WhiteSpace} { } }

    <YYINITIAL> { {Comment} { } }

to:

    <YYINITIAL> { 
      {WhiteSpace} { } 
    }

    <YYINITIAL> { 
      {Comment} { } 
    }

JFlex 1.6.1 was then able to generate the scanner.

I’ll see if I can figure out why the newline requirement was added.

Steve

**Comment by sarowe** [comment]
Here's where the syntax changed: https://github.com/jflex-de/jflex/commit/8a1cb1d#diff-c8ac99d935bdfa1324535aae0d6a59c5R451

I vaguely remember having to introduce the post-open-curly-brace newline requirement in order to handle nested includes in the lexical rules section (https://github.com/jflex-de/jflex/issues/117).

**Comment by sarowe** [comment]
Crap, didn't mean to close the issue when I commented, clicked the wrong button.

**Comment by llbit** [comment]
Is it okay to write `<YYINITIAL> {WhiteSpace} { }`? Will that produce the same scanner as with

    <YYINITIAL> {
      {WhiteSpace} { }
    }

Thanks for looking into this!

**Comment by sarowe** [comment]
Yes, it's okay to write `<YYINITIAL> {WhiteSpace} { }`, and it will produce the same scanner as with the curly-brace-surrounded version.
