### ISSUE TITLE
%unicode 2.0 lexers throw IOOBE on input with surrogate chars

### ISSUE THREAD

**Issue by gregsh** [jflex-de/jflex#199]
Default %unicode means 10x times static memory footprint  (see zzUnpackCMap).
Switching to 2.0 leaves Character.codePointAt() generation intact leading to:

java.lang.ArrayIndexOutOfBoundsException: 65536

in advance() method.

**Comment by sarowe** [comment]
Surrogates aren't characters, but rather code units that as a pair form a character above the basic multilingual plane, aka a supplementary character.  There were no actual defined supplementary characters in Unicode until v3.1.

I think what you want is:

1) Don't use memory required to handle supplementary characters.
2) Handle supplementary characters.

But you can't have both; you must choose.

**Comment by lsf37** [comment]
@gregsh The static memory footprint is larger than `%8bit`, yes (should be something like 256x, actually), but it's insignificant compared to the memory sizes on modern machines and most of it will never be in the working set, so it's not slowing down anything. If it's really important to have a smaller footprint, you can select `%8bit` or similar.

An exception would be more worrying. Do you have any input that can produce one?

**Comment by nicity** [comment]
@sarowe As there are no surrogate characters in Unicode 2.0 we expect them to be handled by lexer (generated with %unicode 2.0) as usual characters, similar to the older versions of JFlex.

@lsf37 as to insignificance of  lexer's memory footprint: I observe each lexer to increase its memory footprint for 2M. In IntelliJ IDEA CE (https://github.com/JetBrains/intellij-community, one of the product we are developing) there are 27 lexers thus memory footprint is increased for 54M, for ultimate product memory increase is more than 90M. Given that default heap size of IntelliJ IDEA on 32 bit java is 500M the lexer's footprint increase is really huge for us!

**Comment by lsf37** [comment]
Alright, I can see how 27 lexers would increase the overhead problem. You can always use `%8bit`, but it sounds like you want Unicode support. As @sarowe says, I don't think you can have both without significant performance degradation. You could imagine some kind of page-table-like sparse translation map, but you'd more than double the memory accesses per scanned character in the innermost scanner loop.

I assume the lexers don't all run at the same time? If yes, we could delay the creation of the `ZZ_CMAP` to creation of the lexer object, i.e. call `zzUnpackCMap` in the constructor instead of static class initialisation time. That would mean, you only need the memory for those lexers that are actually used (depending on when you call the constructor).

**Comment by sarowe** [comment]
> As there are no surrogate characters in Unicode 2.0 we expect them to be handled by lexer (generated with %unicode 2.0) as usual characters, similar to the older versions of JFlex.

@gregsh I think you are right.  I want to investigate more to see what the Unicode standard said about the surrogate block in Unicode 2 and 3, but at a minimum the generated code should not cause AIOOBE.

**Comment by sarowe** [comment]
Related: When implemented #196 will reduce translation map size by 50% (byte[] vs. char[]) in cases where the number of states is less than 257.

**Comment by gregsh** [comment]
Shall we try the same approach java.lang.Character uses for unicode properties?
See generated java.lang.CharacterData classes. They generate multi-stage tables.

````
// java.lang.Character:
    public static boolean isJavaIdentifierStart(int codePoint) {
        return CharacterData.of(codePoint).isJavaIdentifierStart(codePoint);
    }

// CharacterData00.java
    boolean isJavaIdentifierStart(int ch) {
        int props = getProperties(ch);
        return ((props & 0x00007000) >= 0x00005000);
    }

    int getProperties(int ch) {
        char offset = (char)ch;
        int props = A[Y[X[offset>>5]|((offset>>1)&0xF)]|(offset&0x1)];
        return props;
    }

````
Here's the link to the [openjdk tool for building the tables Y, X above](
http://hg.openjdk.java.net/jdk6/jdk6/jdk/file/b577c70564b8/make/tools/src/build/tools/generatecharacter/GenerateCharacter.java). Its javadoc describes the process.

**Comment by lsf37** [comment]
That's what I meant with a page-table like structure, which is just a multi-level table. Like I said, I would expect fairly significant performance impact, because it multiplies the number of memory operations in the innermost lexer loop, which dominates everything, and it's not great for cache locality either.

If it's a correctness issue, i.e. you can actually cause AIOOBE, then we need to do something, and something like this may be the only real option, but if it can be avoided it should. I would not want to slow down all applications because of the memory needs of one, if there are other options we can take. @sarowe have you been able to construct an input that would cause AIOOBE? 

I don't think the specific openjdk method makes much sense for jflex, but something in that direction, possibly. We'd have to figure out a scheme that is tuned for performance and cache locality, taking into account char classes coming out of the spec (which are different for each spec) plus some assumptions on what characters occur most frequently (configurable?). You'd probably also want to be able to trade off size against performance as a developer (i.e. number of lookups vs size of table). Interesting problem, but would take quite a bit of work.

I might of course be wrong about the performance impact. Is there a good way to realistically measure the difference on a typical case without investing months to build a new scheme?

**Comment by gregsh** [comment]
The exception is real, just feed a %unicode 2.0 lexer a text with surrogates, like  U+10437 (𐐷).

Concerning memory footprint, I've followed my own proposal.
Lexer runtime now stays around 20K instead of 1M, sources are of the same size.
We will investigate the performance impact.

**Comment by sarowe** [comment]
> Concerning memory footprint, I've followed my own proposal.

Can you share your implementation?

**Comment by gregsh** [comment]
@sarowe [JetBrains/intellij-community/tools/lexer](https://github.com/JetBrains/intellij-community/tree/master/tools/lexer)

**Comment by sarowe** [comment]
I see only a .jar file there (containing only binary files), and no source?

**Comment by gregsh** [comment]
@sarowe patch file now included

**Comment by gregsh** [comment]
Fork link:
https://github.com/JetBrains/intellij-deps-jflex/commit/6b5c46b71e11d91e978b08d1ffb050f77bf302ea

**Comment by regisd** [comment]
@lsf37 Most flex grammars I have seen are for IntellIj plugins, and it would be great to incorporate their changes to avoid the fork. Let's try to do this for 1.8.0


https://github.com/JetBrains/intellij-community/blob/master/tools/lexer/idea-flex.skeleton

**Comment by lsf37** [comment]
@regisd Yes, we should definitely have a look at this for 1.8.0

**Comment by lsf37** [comment]
Current status is that the exception has been treated already in earlier releases, and that #697 addresses the memory problem. The solution is not quite the same implementation as the one by @gregsh, but it's the same basic idea of a multi-level table, and seems to get the same ~20KB for programming language scanners.

**Comment by lsf37** [comment]
This should now be fixed in https://github.com/jflex-de/jflex/commit/f63cacb5329dd6aa67cc5632dc39e304014f1b26/#697.
