### ISSUE TITLE
`jflex/bin/jflex` cannot resolves jar path.

### ISSUE THREAD

**Issue by fono09** [jflex-de/jflex#251]
# Cause
```bash
$ echo $LANG
ja_JP.UTF-8
$ type /bin/sh
/bin/sh は /bin/sh です
```
Finally, `$PRG` equals `です`.

# Solution
Force `LANG=C` 
```
$ LANG=C type /bin/sh
/bin/sh is /bin/sh
```
or use dirname, pwd to resolve path.

**Comment by lsf37** [comment]
Interesting. I think I fixed the problem by using `$0` directly instead of `type $0`. `dirname` and `pwd` aren't good enough, because they don't resolve symlinks (and `readlink` doesn't work properly on MacOS).

Would you be able to try out replacing the two lines

```
PRG=`type $0`
PRG=${PRG##* }
```

with just `PRG="$0"` in `jflex/bin/jflex`?

**Comment by fono09** [comment]
It fixed. Thank you!
