### ISSUE TITLE
Fixed-width lookbehind (positive, negative)

### ISSUE THREAD

**Issue by idodeclare** [jflex-de/jflex#252]
Hello,

Is fixed-width lookbehind a feasible enhancement request in the current scanning engine design? It would be a useful feature; my use case is qualifying the ends of matches to get a one or two character backtrack. E.g., qualifying a URL match not to end in '.' even though the dot is generally a valid URI character.

Thank you.

**Comment by lsf37** [comment]
Just to make sure we're talking about the same thing: my definition of look-behind would be that in `(?<! a) b` the `a` is the (in this case negative) look-behind, which causes `b` to matched only if it is not preceded by an `a`. The `a` will not be part of the matched text.

If my understanding above is correct, then I think this would be hard to achieve in the current scanning engine. Quite a few parts of the engine currently assume that once a match has concluded its action, that match is fully consumed and will not be needed any more. look-behind obviously violates that.

It would of course be possible to change that, and to analyse a lexer spec for how much look-behind it uses (esp if fixed-wifth), and then keep at least that much of the input around, but you'd still have the problem that then not all runs of the DFA start at the same position. Maybe instead if come up with something that keeps track of the matching states of all look-behinds whenever a full match is finished, and then enable the corresponding DFA start states for the "main" part of the expressions that had look-behind in them for the next run. Something in that direction.

So, I guess the short answer is: it's not feasible in the short term, but if somebody is keen on a small project, one could think more about the details and probably come up with a workable solution.

This probably doesn't help your specific application a lot, sorry..

Depending on how your specific application works, you could try to work with the expression that matches the one before you want to do look-behind and select the set of expressions that are available after using lexical states. That'd basically implement the general idea of above in user space, but if there are lots of different expressions that could come before, that is probably not feasible.

**Comment by idodeclare** [comment]
Thank you for the response.

I am not clear regarding your point: "but you'd still have the problem that then not all runs of the DFA start at the same position."

Also, would a limited convention of trailing-only lookbehind be easier? E.g. `[A-Za-z0-9_\.]+ (?<! \.)` run on `"Abc.mp3."` matching only `"Abc.mp3"`.

**Comment by lsf37** [comment]
The expression you have in the example is look-ahead. That's a bit easier to achieve.

`[A-Za-z0-9_\.]+ / [^\.]`

does almost what you need (the only situation where it would not be right is at the end of file).

**Comment by idodeclare** [comment]
Oh, I'm sorry, I was just illustrating lookbehind — that isn't my actual use case. To further describe the behavior of (the example) `[A-Za-z0-9_\.]+ (?<! \.)`:

* matches `"Abc.mp3"` from `"Abc.mp3."`
* matches `"Abc.mp3.orig"` from `"Abc.mp3.orig"`

**Comment by lsf37** [comment]
I think I'm confused by the syntax in the example. `(?<! \.)` looks like a negative look-behind expression, but would usually precede the rest i.e. `(?<! r) b` not `b (?<! r)`.  Your example seems more like you are talking about a look-ahead expression, though, i.e. the `.` that is not part of the match in the first `Abc.mp3.` is at the end of the input (look-ahead), not the beginning (look-behind).

Which one do you mean? Context on the left (look-behind) or context on the right (look-ahead)?

For context on the left, you have to start matching things before the real match starts. That would a be completely new concept in the engine.

For context on the right, things are different. JFlex does already support positive lookahead (the syntax is `a / b` where `b` is the context, i.e. match `a` only if followed by `b`). We also have negation, so you can say "match `a` only if followed by not-`b`", but that is different to saying "match `a` if not followed by `b`", which is negative look-ahead and from the example is what I think you want (I might be wrong about that). 

I first thought (a while back, in #181) we could support negative lookahead relatively easily, but it turns out it is not as easy as I thought, i.e. it would also require a few new concepts in the scanner engine. One of the main differences is that you want the negative lookahead to be shortest-match, not the longest-match that the engine currently does. In dynamic regexp engines longest/shortest is often a parameter, so it's easy to do either, but in this engine longest match is built in. I don't think it's impossible, but it would be a larger project.

**Comment by idodeclare** [comment]
A lookbehind at the end of a regex serves to shorten the eligible characters. So `\.` that is normally captured via `[A-Za-z0-9_\.]+` is not eligible at the end as a result of `(?<! \.)`.

This `[A-Za-z0-9_\.]+` a simple example, but you might imagine it being a more complex, conditional regex — and the `(?<! \.)` would be a simple way of instructing a possible, slight backtrack at the end of the first's capturing.

But from your note about difficulty in supporting negative lookahead — and judging from the current engine's inability even to do positive lookahead *anywhere* in a regex — I guess it's just as large a project to enhance with another zero-width assertion like the negative lookbehind I'm asking about.

**Comment by lsf37** [comment]
I agree, it'd be a larger project to support this. I'm closing this issue as something we won't be implementing.
