### ISSUE TITLE
bootstrapping issue

### ISSUE THREAD

**Issue by roptat** [jflex-de/jflex#278]
Hi,

I'm trying to package jflex for my distribution. The distribution doesn't accept pre-built binaries, so we try to bootstrap everything from source. Jflex seems to require itself to build LexScan.flex. I'm fine with that because at some point jflex didn't exist, so it  must have used something else. I can build an older version of jflex in order to build the latest version.

However, I tried to build the very first commit of this repository, but even in this version, the .flex file exists. JLex cannot build it because of syntax errors: the file probably uses the new syntax introduced in JFlex that JLex cannot understand.

This is an issue for me, as I can't package jflex that way, and all its dependent packages. Is there an even older version of jflex somewhere that can be built without itself? How did you build the first versions of jflex?

Thanks for your help!

**Comment by lsf37** [comment]
There's no good way to bootstrap it by going back to earlier versions, the syntax changed a few times and there are no instructions any more when and how. The very the first scanner was written manually and never released.

The recommended method for a source distribution would be to build once offline and put the generated LexScan.java into the distribution (possibly also the generated parser if you want to avoid a build dependency on Cup). These generated files used to be part of the repository and the JFlex source distribution for exactly this boot-strap reason, but since we now have a reliable version repository of old binaries, we opted to not keep generated files in version control any more.
