### ISSUE TITLE
7bit switch doesn't work but 8bit and unicode does

### ISSUE THREAD

**Issue by vinhtq115** [jflex-de/jflex#756]
I'm trying to generate a specification for a language using `7bit` switch but JFlex won't generate anything. It always says:

> Reading "vc.flex"
> 0 errors, 0 warnings.
>
> Generation aborted.

When I use `8bit` or `unicode` switch, it works fine.

> Reading "vc.flex"
> Constructing NFA : 276 states in NFA
> Converting NFA to DFA : 
> ...............................................................................
> .......................................................
> 138 states before minimization, 121 states in minimized DFA
> Writing code to "Scanner.java"
> 0 errors, 0 warnings.
> 
> Generation finished successfully.

I'm using JFlex 1.8.1.

**Comment by lsf37** [comment]
Hi @vinhtq115, thanks for the report. Could you append the lex spec or a shortened version of it that has the same symptom?

**Comment by vinhtq115** [comment]
> 
> 
> Hi @vinhtq115, thanks for the report. Could you append the lex spec or a shortened version of it that has the same symptom?

Here you go: https://pastebin.com/R4VcPaGJ

**Comment by lsf37** [comment]
Thanks for that, I can reproduce the problem and confirm this is a bug. Will look into it.

For now, I'd recommend using `%unicode` (or nothing, since unicode is default) instead. I don't know if that is the case for your setting, but often, even if correct input is only 7 or 8 bit, *incorrect* input could still contain other characters. If that happens in the 7 or 8 bit scanner, you'll get an exception that you need to handle outside the scanner, whereas in the unicode scanner, you can write a default rule for unmatched characters that deal with the error case inside the scanner spec.
