### ISSUE TITLE
Support returning multiple tokens in one action

### ISSUE THREAD

**Issue by 0xekez** [jflex-de/jflex#776]
It is occasionally desirable to return multiple terminals from one action. [This](https://stackoverflow.com/questions/42434603/how-can-flex-return-multiple-terminals-at-one-time) StackOverflow question gives an example of this and a couple options for handling this with Flex. In particular, it lists this nonblock do-loop in Fortran:
```fortran
DO 20 I=1, N      ! line 1
DO 20 J=1, N      ! line 2
    ! more codes
20  CONTINUE      ! line 4
```
In that example, the last 20 serves as the end of both the first and second `DO` loops. It is then desirable to emit two `ENDDO` terminals when the 20 is matched.

The Flex solution seems to be to insert some code into the `yylex` method that first returns from a token queue and then tries to match tokens. When you'd like to return two tokens you just return the first one and put the second one in the queue. 

Does Jflex provide a way to do this or otherwise support this use case?

**Comment by lsf37** [comment]
You could actually probably simulate pushing different input into the input stream by using nested input streams as in the nested input stream skeleton JFlex uses for its own scanner. That is, instead of pushing anything into the current input stream, you open a new nested string input stream that contains the input you want to re-match.

Unlikely to be efficient and I wouldn't recommend it, but I guess it could be done.
