### ISSUE TITLE
[Help] Newbie question

### ISSUE THREAD

**Issue by AgustinNormand** [jflex-de/jflex#940]
Hi,

I've been searching for 2 hours and I couldn't find an answer, so that's why I'm here.

I'm trying to avoid doing this:
```
{While_keyword} {System.out.println("While_keyword token found, lex= "+ yytext());
{If_keyword} {System.out.println("If_keyword token found, lex= "+ yytext());
{Print_keyword} {System.out.println("Print_keyword token found, lex= "+ yytext());
```

So I did something like this:
```
{While_keyword}     |
{If_keyword}        |
{Print_keyword} {System.out.println("Token found, lex= "+ yytext());
```

But I want to show if the token is "While_keyword" or "If_keyword" or "Print_keyword". I couldn't find how to do it. Can someone help me?

In other words, I want to retrieve the expression matched, in the action.

Thanks!

**Comment by lsf37** [comment]
`yytext()` is the string matched. There is no such thing as an expression matched, you'd usually have different actions for different expressions, for example:

```jflex
{While_keyword} { return WHILE; }
{If_keyword} { return IF; }
{Print_keyword} { return PRINT; }
```

(where `WHILE`, `IF`, `PRINT`, are constants you would define elsewhere, e.g. an enumeration or just specific `ints`).

Instead of `return` you can also run any other code that you need.
